### ISSUE TITLE
subsonic download/update not working

### ISSUE THREAD

**Issue by Stoney49th** [OpenMediaVault-Plugin-Developers/openmediavault-subsonic#1]
Hi,

i installed the plugin yesterday and noticed that the update subsonic (aka. download the package and install it) doesn't work... instead of downloading a "loading..." is displayed two times and than the updater stops without error but also doesn't do anything. I then went ahead and downloaded and installed manually (wget && dpkg -i) without any issue and its working fine since then.

**Comment by cptjhmiller** [comment]
The current code looks for the latest release using grep command to get the version number, unfortunately the latest version has a 3 point version number (5.2.1) and this breaks the grep command.
I have fixed that locally but need to get to grips with the proxy setting as some screens do not show.
