### ISSUE TITLE
HTTPS config

### ISSUE THREAD

**Issue by Stoney49th** [OpenMediaVault-Plugin-Developers/openmediavault-subsonic#2]
Hi,

the current subsonic config is missing the HTTPS port setup, and so is the gui with a port assignment option for https. I know that its not straight forward to install a different ssl key & cert with java but there should at least be the config option in the gui. If it is possible without mayor script clusterfuck, a option to setup the cert & key would be nice.

**Comment by cptjhmiller** [comment]
Its uses Subsonics key and cert.
I plan to add that at a later date.

**Comment by Stoney49th** [comment]
Ok, how about the https-port feature? The cert is not as critical for now, but it really bugs me to manually fixup the config everytime it gets re-generated...I've had a quick look at the source and theres already some code in there for the port. Why not add a second text input for the port and check if it is blank/number entered? Would be nice :) 

Edit: talking about line 77ff in mkconf

**Comment by cptjhmiller** [comment]
I do not understand, There is an option for the port (default 4040) if https is selected then it will use that for for ssl if not it will use that port for normal operation, there is no point in adding another port solely for https.

**Comment by Stoney49th** [comment]
? But theres no button in the omv-gui to enable this? Or how is this controlled by a subsonic config?

**Comment by cptjhmiller** [comment]
General settings
Enable - Subsonic can take a few seconds to start. (check box)
Show Tab - Show tab containing Subsonic web interface frame. (check box)

Port    (number field)

HTTPS - Auto enable HTTPS. (check box)
Proxy Pass - Enable this to access via OMV_IP/subsonic

Version info - Current version is 5.2.1, there is no new update available.

That's what I see from my GUI

**Comment by Stoney49th** [comment]
Oh, i'm on version 1.0.5 and those options are missing. Are they in a newer version of the plugin?

**Comment by cptjhmiller** [comment]
1.0.6 is the latest version, its in the downloads testing repo

**Comment by Stoney49th** [comment]
I've just installed that version, but I can't enable ssl. Instead I get this error message: "You have SSL enabled for the main UI, Do NOT enable it here as well."

The webgui is on a non-standard port with SSL in my case (as well as the non-ssl version), so there won't be any conflict here. If the plugin just uses port 443 if the checkbox is set, this is rather strange, because this limits the user quiet a bit...in my case, I have 3 webapps on ssl, all on different ports.

It would be really great if one could setup the ssl port, just like with the nginx-plugin. Maximum flexability, without the danger of screwing up the webgui.

**Comment by cptjhmiller** [comment]
The port used is the port number in the box (either http or https)

The warning you got was (I think) a mistake, it should only warn if using a proxy and you try to enable SSL when SSL is enabled for the webui. It maybe that I did test that scenario and I did not work and that's why you get the error (I can't remember TBH) I will do some testing.

**Comment by Stoney49th** [comment]
Sorry for the long absence here...

I just installed 1.0.7 from the testing repo and it seems to fix my issue and now works perfectly with SSL. Big thanks for the effort with the plugin...I'll keep using it and report any bugs, but so far everything seems functional :)

**Comment by cptjhmiller** [comment]
Thanks for letting me know.
