### ISSUE TITLE
Subsonic mkconf script

### ISSUE THREAD

**Issue by lu6fer** [OpenMediaVault-Plugin-Developers/openmediavault-subsonic#4]
The last version of subsonic is 5.2.1, but the mkconf script update function wants to find [0-9].[0-9]
So no download at all from this script.
May be change the regexp to match extra version number, 

``` shell
\egrep subsonic-[0-9].[0-9]?.[0-9]?.de
```

or the match '.deb' line because there is no more beta version in download page

``` shell
egrep "\.deb"
```

instead of 

``` shell
\grep subsonic-[0-9].[0-9].deb
```

**Comment by cptjhmiller** [comment]
I fixed this locally with
\grep subsonic-[0-9].*.deb

I have other issues to fix first and that's why its not been committed yet.
