### ISSUE TITLE
typo in postrm file

### ISSUE THREAD

**Issue by snow3461** [OpenMediaVault-Plugin-Developers/openmediavault-subsonic#6]
Trying to uninstall subsonic after I gave it a try, I have an error with postrm script exiting with value 1.

Looking at the postrm file in this repo, to investigate, i found a typo [there](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-subsonic/blob/master/debian/postrm#L20)
mention of sickbeard instead of subsonic....so user is not delete unless you have sickbeard user existing.

I believe it is not responsible for my error, still investigating.

**Comment by ryecoaaron** [comment]
Fixed in commit 97bddb1631c7dec57257172b099a22044bd86824
